server:
  port: 9296
spring:
  application:
    name: CONFIG-SEERVER

  cloud:
    config:
      server:
        git: 
          uri: https://github.com/bngferoz/configProperties
          clone-on-start: true
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://172.17.0.1:8761/eureka}
    
